#!/usr/bin/env bash
#Set up nginx web server into 4521-web-01 server.
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/sites-available/
sudo chmod 777 /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
