#!/usr/bin/env bash
#Set up nginx web server into 4521-web-01 server.
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chmod 777 /etc/nginx/sites-available/
sudo chmod 777 /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/ a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

# 404-error-page set up
echo "Ceci n'est pas une page" | sudo tee /var/www//html/bedo_404.html
sed -i "/listen 80 default_server;/ a error_page 404 /bedo_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
